# Generated by Django 4.0.4 on 2023-03-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/products/', verbose_name='Фото товара'),
        ),
    ]
